spring:
  profiles:
    active: local
server:
  port: 8082
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

---
spring:
  profiles: local
  flyway:
    enabled: true
    username: sa
    locations: ['filesystem:./migration']
  h2:
  console:
    enabled: true
    path: /h2-console
    settings:
      trace: false
      web-allow-others: false
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework: debug
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace